### ISSUE TITLE
AFM

### ISSUE THREAD

**Issue by shqzpdx** [ZiyaoGeng/RecLearn#20]
afm代码里好像没有看到一次项w0+wx

**Comment by chenxli** [comment]
而且好像没有dense inputs的交叉

**Comment by ZiyaoGeng** [comment]
回答以下上述两个问题：
1. 加一此项有点麻烦，需要one-hot，在进行逻辑回归（可以自行尝试下，参考FM或者有其他更好的方法）
2. dense inputs不知道加在哪个位置，也可以尝试下（我尝试的结果都不大好）

**Comment by chenxli** [comment]
谢谢啦~我加上去了，后面跑一下看看效果



在 2021-01-08 14:29:16，"潜心" <notifications@github.com> 写道：

回答以下上述两个问题：

加一此项有点麻烦，需要one-hot，在进行逻辑回归（可以自行尝试下，参考FM或者有其他更好的方法）
dense inputs不知道加在哪个位置，也可以尝试下（我尝试的结果都不大好）

**Comment by ZiyaoGeng** [comment]
> 谢谢啦~我加上去了，后面跑一下看看效果 在 2021-01-08 14:29:16，"潜心" <notifications@github.com> 写道： 回答以下上述两个问题： 加一此项有点麻烦，需要one-hot，在进行逻辑回归（可以自行尝试下，参考FM或者有其他更好的方法） dense inputs不知道加在哪个位置，也可以尝试下（我尝试的结果都不大好） — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，如果有更好的结果可以分享下，或者request也可以。另外，重新检查了下，发现attention的部分写错了（不过更正后效果还是挺差的），另外对特征交叉部分也进行了更改，原来的方式太慢了，参考了PNN的特征交叉方法。

**Comment by chenxli** [comment]
同学，你好，AFM我加了dense embedding + linear part，测试集AUC提升了，达到了0.77。（不过dense embedding后来一想还比较粗暴。。）



在 2021-01-08 14:36:11，"潜心" <notifications@github.com> 写道：

谢谢啦~我加上去了，后面跑一下看看效果 在 2021-01-08 14:29:16，"潜心" notifications@github.com 写道： 回答以下上述两个问题： 加一此项有点麻烦，需要one-hot，在进行逻辑回归（可以自行尝试下，参考FM或者有其他更好的方法） dense inputs不知道加在哪个位置，也可以尝试下（我尝试的结果都不大好） — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，如果有更好的结果可以分享下，或者request也可以。另外，重新检查了下，发现attention的部分写错了（不过更正后效果还是挺差的），另外对特征交叉部分也进行了更改，原来的方式太慢了，参考了PNN的特征交叉方法。

**Comment by FlamingJay** [comment]
借楼问一下，AFM中，若模式为max时，应该使用的是reduce_max，而不是reduce_sum
