### ISSUE TITLE
ml-1m数据集链接失效了

### ISSUE THREAD

**Issue by vlenlee** [ZiyaoGeng/RecLearn#41]
给出的几个数据集链接中ml-1m数据集失效了，能不能补一下数据集呢，感谢

**Comment by ZiyaoGeng** [comment]
ml-1m可以自己找下


| |
zggzy1996
|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年06月19日 ***@***.***> 写道：

给出的几个数据集链接中ml-1m数据集失效了，能不能补一下数据集呢，感谢

**Comment by vlenlee** [comment]
> ml-1m可以自己找下 | | zggzy1996 | | ***@***.*** | 签名由网易邮箱大师定制 在2021年06月19日 ***@***.***> 写道： 给出的几个数据集链接中ml-1m数据集失效了，能不能补一下数据集呢，感谢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

下载的原版ml-1m数据集不需要进行任何处理就可以直接用吗

**Comment by ZiyaoGeng** [comment]
是的，直接可以用，数据是经过处理的


| |
zggzy1996
|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年06月20日 ***@***.***> 写道：

ml-1m可以自己找下 | | zggzy1996 | | @.*** | 签名由网易邮箱大师定制 在2021年06月19日 @.***> 写道： 给出的几个数据集链接中ml-1m数据集失效了，能不能补一下数据集呢，感谢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

下载的原版ml-1m数据集不需要进行任何处理就可以直接用吗
